### ISSUE TITLE
IterableExtension sortedBy doesn't permit sorting by int without workaround

### ISSUE THREAD

**Issue by trinarytree** [dart-lang/collection#271] opened 2023-02-22 06:34 UTC
```dart
import 'package:collection/collection.dart';

void main() {
  [2, 1].sortedBy((i) => i);
}
```
yields
```
Error: Inferred type argument 'int' doesn't conform to the bound
'Comparable<K>' of the type variable 'K' on 'IterableExtension|sortedBy'.
```
sorting by an `int` is a pretty important use case.
the problem seems to be that `sortedBy` insists that its generic param `K` extend `Comparable<K>`
and `int` doesn't extend `Comparable<int>`.  rather, it extends `Comparable<num>`.

workaround:
```dart
  [2, 1].sortedBy<num>((i) => i);
```

the workaround doesn't seem like it should be the end of this story.
i feel like the first example should just work.   perhaps one could see this as a problem with the type inference system,
as in, why can't it figure out that `K` perhaps should be bound to a super class (`num`) of the exact type (`int`)
returned by the `keyOf` function?

**Comment by natebosch** [comment] 2023-02-23 02:39
Closing as a duplicate of https://github.com/dart-lang/sdk/issues/43763

I don't think there is anything we can do from the package side.

**Closed by natebosch** 2023-02-23 02:39 UTC
Labels: question

**Comment by eseidel** [comment] 2023-10-10 15:32
I think simply documenting this in the sortedBy docs would go a long way. :)

**Comment by natebosch** [comment] 2023-10-10 19:33
> I think simply documenting this in the sortedBy docs would go a long way

Why `sortedBy` but not `isSortedby`, `binarySearchBy`, `lowerBoundBy`, or `sortBy`?

**Comment by eseidel** [comment] 2023-10-10 23:48
> > I think simply documenting this in the sortedBy docs would go a long way
> 
> Why `sortedBy` but not `isSortedby`, `binarySearchBy`, `lowerBoundBy`, or `sortBy`?

No good reason.  Was mostly trying to avoid "perfect being the enemy of the good" by documenting the one method through which myself and two other colleagues had independently encountered this error. 🤣   Happy to see something more systemic, just was trying to be helpful.  I've personally not used any of the 4 other methods, but I have no data to say which are more/less common.

**Comment by natebosch** [comment] 2023-10-11 18:52
I think if we do decide to address this with a note in the doc comment we can easily enough make it a template and repeat it in each impacted method.

Once we hear back from the analyzer team on the feasibility for making the diagnostic more informative we can make a choice on landing the PR.
